services:
  psql_bp:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data
  keyclock:
    build:
      context: ./setup/docker/keycloack
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - psql_bp
      - db-init-keycloack
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://psql_bp:5432/keycloack
      KC_DB_USERNAME: ${DB_USERNAME}
      KC_DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8443:8443"
      - "9000:9000"
    command:
      - start
      - --optimized
      - --hostname=localhost
      - --import-realm
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "redis_password"]
  db-init-keycloack:
    image: postgres:17
    depends_on:
      - psql_bp
    environment:
      PGPASSWORD: ${DB_PASSWORD}
    entrypoint: >
      bash -c "
        until pg_isready -h psql_bp -U ${DB_USERNAME}; do sleep 2; done;
        psql -h psql_bp -U ${DB_USERNAME} -d postgres -c 'CREATE DATABASE keycloack;' || true
      "


volumes:
  psql_volume_bp:
